### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by onbjerg** [1Hive/uniswap-interface#18]
MetaMask is causing a lot of issues for us, which results in a lot of esoteric errors for the end-user. We can alleviate some of the support pain by implementing better error messages, specifically for these cases:

- **The gas price is too low**: Sometimes MetaMask won't correctly determine a gas price since it has no official xDai support
- **Transaction with same nonce already exists**: I'm not sure if this is super prevalent, but sometimes the nonce is incorrect as well
- **Fallback**: The fallback should be a bit better than what we have currently (currently, an error is just some generic string with [object Object] at the end

Relevant lines of code:

https://github.com/1Hive/uniswap-interface/blob/7c80d29596737f3246e495f96af68470081bb132/src/hooks/useSwapCallback.ts#L232-L238

**Comment by ceresbzns** [comment]
We can come back to this.
