### ISSUE TITLE
Wrong decimal count in tokenlist for USDT

### ISSUE THREAD

**Issue by jeffcaden** [1Hive/uniswap-interface#19]
The value for USDT is not shown correctly. Instead of showing 300 it shows 0.0000000003.

I think the issue is with the honeswap tokenlist (http://tokens.honeyswap.org/), which uses 18 decimals for USDT.
It should be 6.

    {
      "name": "Tether on xDai",
      "address": "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "symbol": "USDT",
      "decimals": 18,
      "chainId": 100,
      "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png"
    },

**Comment by onbjerg** [comment]
Going to be fixed in https://github.com/1Hive/default-token-list/pull/10

Thanks for the report and sorry for the inconvenience :)

**Comment by onbjerg** [comment]
Should be fixed in the latest Honeyswap tokenlist!
