### ISSUE TITLE
Host token list on IPFS

### ISSUE THREAD

**Issue by onbjerg** [1Hive/uniswap-interface#4]
We should host the default token list on IPFS and update it in both this repository and Honeyswap Info, as it seems like some of the users of Honeyswap are blocked from downloading the token list from GitHub.

**Comment by crisog** [comment]
Configured the default tokenlist repo so it builds and publish the list to IPFS, so this can now be closed.

URL: http://tokens.honeyswap.org/
Repository: https://github.com/1Hive/default-token-list
