### ISSUE TITLE
Total Number of Tokens Issued for contract incorrect  

### ISSUE THREAD

**Issue by stevecarrol** [1Hive/uniswap-interface#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stevecarrol** [comment]
This API call should provide the result 25K for the total number of tokens issued for the HNY contract 
https://blockscout.com/poa/xdai/api/?module=stats&action=tokensupply&contractaddress=0x71850b7e9ee3f13ab46d67167341e4bdc905eef9
Instead, it provides the number  24183197363957605806137

**Comment by crisog** [comment]
> This API call should provide the result 25K for the total number of tokens issued for the HNY contract
> https://blockscout.com/poa/xdai/api/?module=stats&action=tokensupply&contractaddress=0x71850b7e9ee3f13ab46d67167341e4bdc905eef9
> Instead, it provides the number 24183197363957605806137

Hey @stevecarrol, this big number represents the WEI amount. You can use this converter if you to get the regular representation. (https://eth-converter.com/)

![image](https://user-images.githubusercontent.com/40803711/94369300-e02c9c80-00b6-11eb-835b-9d66b27fb38c.png)
